name = "glans"
version = "0.0.1"
target = "erlang"
description = "Ahead of time tree-sitter syntax highlighting for lustre"
licences = ["MIT"]
repository = { type = "github", user = "ollema", repo = "glans" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.3.6 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
